CITIES = {
    'London': 'A',
    'Trier': 'B',
    'Paris': 'C',
    'Marseilles': 'D',
    'Saguntum': 'E',
    'New Carthage': 'F',
    'Ravenna': 'G',
    'Roma (Rome)': 'H',
    'Syracuse': 'I',
    'Philippi': 'J',
    'Pharsalus': 'K',
    'Actium': 'L',
    'Athens': 'M',
    'Byzantium/Constantinople': 'N',
    'Nicomedia': 'O',
    'Pergamum/Pergamon': 'P',
    'Edessa': 'Q',
    'Antioch': 'R',
    'Seleucia-Ctesiphon': 'S',
    'Sidon': 'T',
    'Jerusalem': 'U',
    'Alexandria': 'V',
    'Memphis': 'W',
    'Carthage': 'X',
    'Cirta': 'Y',
    'Cadiz': 'Z',
}