PROVINCES = {
    'Britannia':'2',
    'Germania inferior':'3',
    'Belgica':'4',
    'Lugdunensis':'5',
    'Germania superior':'6',
    'Aquitania':'7',
    'Alpes poeninae':'8',
    'Alpes cottiae':'9',
    'Alpes maritimae':'10',
    'Narbonensis':'11',
    'Tarraconensis':'12',
    'Lusitania':'13',
    'Baetica':'14',
    'Italia (Italy)':'15',
    'Corsica':'16',
    'Sardinia':'17',
    'Raetia':'18',
    'Noricum':'19',
    'Pannonia superior':'20',
    'Pannonia inferior':'21',
    'Dalmatia (=Illyricum)':'22',
    'Dacia':'23',
    'Moesia superior':'24',
    'Moesia inferior':'25',
    'Thracia (Thrace)':'26',
    'Macedonia':'27',
    'Epirus':'28',
    'Achaea':'29',
    'Creta (Crete)':'30',
    'Bithynia et Pontus':'31',
    'Asia':'32',
    'Galatia':'33',
    'Lycia et Pamphylia':'34',
    'Cappadocia':'35',
    'Cilicia':'36',
    'Armenia':'37',
    'Assyria':'38',
    'Mesopotamia':'39',
    'Syria':'40',
    'Cyprus':'41',
    'Iudaea (Judea)':'42',
    'Arabia':'43',
    'Aegyptus (Egypt)':'44',
    'Cyrenaica':'45',
    'Africa Proconsularis':'46',
    'Numidia':'47',
    'Mauretania Caesariensis':'48',
    'Mauretania Tingitana':'49',
    'Sicilia (Sicily)':'50'
}

CITIES = {
    'London': 'A',
    'Trier': 'B',
    'Paris': 'C',
    'Marseilles': 'D',
    'Saguntum': 'E',
    'New Carthage': 'F',
    'Ravenna': 'G',
    'Roma (Rome)': 'H',
    'Syracuse': 'I',
    'Philippi': 'J',
    'Pharsalus': 'K',
    'Actium': 'L',
    'Athens': 'M',
    'Byzantium/Constantinople': 'N',
    'Nicomedia': 'O',
    'Pergamum/Pergamon': 'P',
    'Edessa': 'Q',
    'Antioch': 'R',
    'Seleucia-Ctesiphon': 'S',
    'Sidon': 'T',
    'Jerusalem': 'U',
    'Alexandria': 'V',
    'Memphis': 'W',
    'Carthage': 'X',
    'Cirta': 'Y',
    'Cadiz': 'Z'
}

DATES = {
    'RANGE Second Punic War': '218-201',
    'Battles of Ticinum and Trebia': '218',
    'Battle of Lake Trasimene': '217',
    'Battle of Cannae' : '216',
    'Hannibal takes Capua and is supported by Philip V of Macedon': '215',
    'defeat of Syracuse; death of Archimedes': '212',
    'defeat of Hasdrubal at Metaurus River': '215',
    'Romans conquer Spain': '206',
    'end of First Macedonia War': '205',
    'Scipio invades Africa': '204',
    'Hannibal recalled': '203',
    'Battle of Zama': '202',
    'treaty signed after second punic war': '201',
    'Spain made into two provinces': '197',
    'Philip V defeated at Cynoscephalae (Second Macedonian War)': '197',
    'Antiochus III of Syria defeated at Magnesia': '190',
    'Third Macedonian War ends at Pydna': '168',
    'Illyricum made a province': '167',
    'RANGE Third Punic War; destruction of Carthage; Africa made a province': '149-146',
    'Fourth Macedonian War ends': '148',
    'revolt of Achaean League; Achaea and Macedonia made a province': '146',
    'Tiberius Gracchus, tribune of the plebs': '133',
    'RANGE Gaius Gracchus, tribune of the plebs': '123-122',
    'RANGE Gaius Marius, consul six times, five times in a row (104-100)': '107-100',
    'RANGE Social War': '91-87',
    'siege of Rome': '82',
    'RANGE Sulla dictator': '81-80',
    'RANGE revolt of Spartacus in Italy': '73-71',
    'Pompey and Crassus consuls': '70',
    'Gaius Julius Caesar consul': '59',
    'Caesar begins first five-year command in Gaul': '58',
    'RANGE Caesar’s conquest of Britain': '55-54',
    'Crassus killed at Carrhae against Parthians': '53',
    'Gaul made a province': '51',
    'DAY (# month year) senate declares martial law against Caesar': '7 january 49',
    'DAY (# month year) Caesar crosses the Rubicon River, thereby declaring civil war': '11 january 49',
    'Pompey defeated at Pharsalus by Caesar': '48',
    'DAY (# month year) Caesar assassinated': '15 march 44'
}