PROVINCES = {'Britannia':'2',
    'Germania inferior':'3',
    'Belgica':'4',
    'Lugdunensis':'5',
    'Germania superior':'6',
    'Aquitania':'7',
    'Alpes poeninae':'8',
    'Alpes cottiae':'9',
    'Alpes maritimae':'10',
    'Narbonensis':'11',
    'Tarraconensis':'12',
    'Lusitania':'13',
    'Baetica':'14',
    'Italia (Italy)':'15',
    'Corsica':'16',
    'Sardinia':'17',
    'Raetia':'18',
    'Noricum':'19',
    'Pannonia superior':'20',
    'Pannonia inferior':'21',
    'Dalmatia (=Illyricum)':'22',
    'Dacia':'23',
    'Moesia superior':'24',
    'Moesia inferior':'25',
    'Thracia (Thrace)':'26',
    'Macedonia':'27',
    'Epirus':'28',
    'Achaea':'29',
    'Creta (Crete)':'30',
    'Bithynia et Pontus':'31',
    'Asia':'32',
    'Galatia':'33',
    'Lycia et Pamphylia':'34',
    'Cappadocia':'35',
    'Cilicia':'36',
    'Armenia':'37',
    'Assyria':'38',
    'Mesopotamia':'39',
    'Syria':'40',
    'Cyprus':'41',
    'Iudaea (Judea)':'42',
    'Arabia':'43',
    'Aegyptus (Egypt)':'44',
    'Cyrenaica':'45',
    'Africa Proconsularis':'46',
    'Numidia':'47',
    'Mauretania Caesariensis':'48',
    'Mauretania Tingitana':'49',
    'Sicilia (Sicily)':'50'
}